### PR TITLE
Ensure consistent use of versions during pagination

### LINKED ISSUE #590: Error when listing large directory with versions=True
In some cases, listing a large directory with `versions=True` fails with a cryptic error. This only happens when results are paginated.

Here's an example:
```
>>> import gcsfs
>>> fs = gcsfs.GCSFileSystem(version_aware=True)
>>> ll = fs.ls("gcs://dql-50k-laion-files/000003/", versions=True)
_request non-retriable exception: Invalid argument., 400
Traceback (most recent call last):
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/retry.py", line 123, in retry_request
    return await func(*args, **kwargs)
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/core.py", line 430, in _request
    validate_response(status, contents, path, args)
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/retry.py", line 110, in validate_response
    raise HttpError(error)
gcsfs.retry.HttpError: Invalid argument., 400
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ronan/.pyenv/versions/dql-3.10/lib/python3.10/site-packages/fsspec/asyn.py", line 118, in wrapper
    return sync(self.loop, func, *args, **kwargs)
  File "/Users/ronan/.pyenv/versions/dql-3.10/lib/python3.10/site-packages/fsspec/asyn.py", line 103, in sync
    raise return_result
  File "/Users/ronan/.pyenv/versions/dql-3.10/lib/python3.10/site-packages/fsspec/asyn.py", line 56, in _runner
    result[0] = await coro
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/core.py", line 998, in _ls
    for entry in await self._list_objects(
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/core.py", line 564, in _list_objects
    items, prefixes = await self._do_list_objects(
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/core.py", line 638, in _do_list_objects
    return await self._sequential_list_objects_helper(
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/core.py", line 753, in _sequential_list_objects_helper
    page = await self._call(
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/core.py", line 437, in _call
    status, headers, info, contents = await self._request(
  File "/Users/ronan/.pyenv/versions/dql-3.10/lib/python3.10/site-packages/decorator.py", line 221, in fun
    return await caller(func, *(extras + args), **kw)
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/retry.py", line 158, in retry_request
    raise e
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/retry.py", line 123, in retry_request
    return await func(*args, **kwargs)
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/core.py", line 430, in _request
    validate_response(status, contents, path, args)
  File "/Users/ronan/devel/iterative/gcsfs/gcsfs/retry.py", line 110, in validate_response
    raise HttpError(error)
gcsfs.retry.HttpError: Invalid argument., 400
```

### PR DESCRIPTION
**Pull request by rlamy**
Fixes #590.

I didn't add a test since I don't know how to write a sensible unit-test for paginated results.

### CODE REVIEW

**Comment by martindurant** [comment]
So that I understand what's going on here: listing of files should either be versioned or not, because it's not anticipated to be able to "list" a specific file generation? We usually do allow list of a specific path, though (would return a list of one item, essentially the same as info() ), so we need to make sure that that still works. Of course, such a listing with a specified generation would never be paginated.

To test, the [call](https://docs.aws.amazon.com/AmazonS3/latest/API/API_ListObjectsV2.html#API_ListObjectsV2_RequestSyntax) accepts `max-keys`, so that could be set to a small number for the same of a test. I'm not immediately sure if that would need to be a monkeypatch. (having said that, pushing >1000 files to a local moto server shouldn't take that long at all)

**Comment by rlamy** [comment]
The only use of `generation` is to decide whether to ask for versions. I guess it's indeed to support single-file `ls`. The issue seems to be that the page token may be rejected (depending on bucket settings, auth method, ...) if `versions` isn't set in the same way as in the first call.

I tried your suggestion for testing, but it looks like gcs-fake-server (this is GCS, not S3 :wink:) doesn't ever return paginated results.

**Comment by rlamy** [comment]
Thank you! Any idea of when the next release will be?

**Comment by martindurant** [comment]
> when the next release will be

As soon as we've sorted out the aiobotocore version pinning issue in s3fs (because they are always released together with fsspec)

**Pull request merged**
